services:
    db_mysql:
        image: mysql:5.7.40
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            - MYSQL_DATABASE=tttn
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - db:/var/lib/mysql

    # backend_nodejs:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     depends_on:
    #         - db_mysql
    #     image: tdq11111/backend_nodejs
    #     restart: unless-stopped
    #     working_dir: /app
    #     volumes:
    #         - /BackEnd/node_modules
    #     ports:
    #         - 8080:8080
    #     environment:
    #         - DB_HOST=db_mysql
    #         - DB_DATABASE_NAME=huongdichvu
    #         - DB_USERNAME=root
    #         - DB_PORT=3306
    #         - DB_PASSWORD=123456
    #         - DB_DIALECT=mysql
    #     healthcheck:
    #         test: apk add curl --fail -s http://localhost:8080/api/
    #         interval: 30s
    #         timeout: 10s
    #         retries: 5
volumes:
    db:
