version: "3.8"
services:
    db_mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3308:3306"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        networks:
            - health-booking-network

    backend_nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db_mysql
        image: tdq11111/backend_nodejs_medical
        restart: unless-stopped
        working_dir: /app
        volumes:
            - /backend_nodejs/node_modules
        ports:
            - 8080:8080
        environment:
            - DB_HOST=db_mysql
            - DB_DATABASE_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PORT=3306
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DIALECT=${DB_DIALECT}
        expose:
            - 8080
        env_file:
            - .env
        networks:
            - health-booking-network

volumes:
    db:

networks:
    health-booking-network:
        external: true
#docker network create health-booking-network
#docker compose -p backend_health-booking up -d
