version: "3.8"
services:
    db_mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3308:3306"
        environment:
            - MYSQL_DATABASE=tttn
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - db:/var/lib/mysql

    backend_nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db_mysql
        image: tdq11111/backend_nodejs_medical
        restart: unless-stopped
        working_dir: /app
        volumes:
            - /BackEnd/node_modules
        ports:
            - 8080:8080
        environment:
            - DB_HOST=db_mysql
            - DB_DATABASE_NAME=tttn
            - DB_USERNAME=root
            - DB_PORT=3306
            - DB_PASSWORD=123456
            - DB_DIALECT=mysql
        expose:
            - 8080
volumes:
    db:
#docker compose -p backend_health-booking up -d